// <auto-generated />
namespace BeSide.DataAccess.SqlDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class F : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(F));
        
        string IMigrationMetadata.Id
        {
            get { return "201808082128236_F"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
